// TIMER ACTIONS:
export const SET_CURRENT_TIME = "SET_CURRENT_TIME"

// TIME SETTINGS:
export const SET_CURFEW_TIME = "SET_CURFEW_TIME"
export const SET_CURFEW_ALERT_TIME = "SET_CURFEW_ALERT_TIME"
export const SET_CURFEW_ALERT_REMINDER = "SET_CURFEW_ALERT_REMINDER"

// LOCATION ACTIONS:
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION"
export const SET_SAFE_AREA = "SET_SAFE_AREA"
export const UNSET_SAFE_AREA = "UNSET_SAFE_AREA"
export const SET_SAFE_AREA_DIAMETER = "SET_SAFE_AREA_DIAMETER"
export const CHANGE_SAFE_AREA_DIAMETER = "CHANGE_SAFE_AREA_DIAMETER"
export const TOGGLE_IS_HOME = "TOGGLE_IS_HOME"

// MODAL ACTIONS:
export const OPEN_MODAL = "OPEN_MODEL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const TOGGLE_MODAL = "TOGGLE_MODAL"

// AUDIO ACTIONS:
export const LOAD_SOUND = "LOAD_SOUND"
export const UNLOAD_SOUND = "UNLOAD_SOUND"

// APP CONFIG ACTIONS:
export const TOGGLE_APP_IS_SILENT = "TOGGLE_APP_IS_SILENT"
export const TOGGLE_APP_IS_OFF = "TOGGLE_APP_IS_OFF"
export const TOGGLE_CAR_MODE_IS_ON = "TOGGLE_CAR_MODE_IS_ON"